pom.xml, src/main/java/com/sysdig/jenkins/plugins/sysdig/AnchoreBuilder.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/BuildConfig.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/BuildWorker.java, src/main/resources/com/sysdig/jenkins/plugins/sysdig/AnchoreBuilder/global.jelly
Minor (and long awaited) change, to modify the way the plugin global credentials are being used. Instead of plain text, we now fetch the credentials from the credentials store, the same way as the per-job configuration is handled.
=> Global creds

README.md, pom.xml
This PR updates the Jenkins documentation from the old wiki to GitHub (https://jenkins.io/doc/developer/publishing/wiki-page/#migrating-from-wiki-to-github).
=> Update the Jenkins documentation for GitHub

README.md, src/main/java/com/sysdig/jenkins/plugins/sysdig/RemoteInlineScanningExecution.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/client/SysdigSecureClientImpl.java, src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder/global.jelly
This PR improves 3 things in the Inline Scanning procedure:
1. Do not name the container that executes the Inline Scanning, as there could be other scanning processes in the same host. Also, auto-remove it after 1h if the scanning has failed to execute, for an exception or similar. The container will still be executed in background with a sleep, so no resources will be consumed by the container.
2. Update the URL to upload the metadata to the synchronous endpoint as is more reliable and does not suffer from the timeouts the asynchronous has. If the sync endpoint does not exist (404), fall back to the async one.
3. Use the anchore-engine image instead of the inline-scan one, so instead of downloading an image of 1GB, it downloads 100MB only.
=> feat: Some Inline Scanning improvements

src/main/java/com/sysdig/jenkins/plugins/sysdig/RemoteInlineScanningExecution.java
Having a ":" in the .tar filename triggers an error in the internal skopeo command that Anchore analyzer runs.
Replace all apparitions of ":", "." and "/".
=> Replace all :, . and / for the .tar filename

pom.xml
This PR adds the guava dependency explicitly to solve this issue:
```
java.lang.ClassNotFoundException: com.google.common.io.BaseEncoding
at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Caused: java.lang.NoClassDefFoundError: com/google/common/io/BaseEncoding
at com.github.dockerjava.core.exec.AbstrDockerCmdExec.registryAuth(AbstrDockerCmdExec.java:45)
at com.github.dockerjava.core.exec.AbstrDockerCmdExec.resourceWithAuthConfig(AbstrDockerCmdExec.java:77)
at com.github.dockerjava.core.exec.AbstrDockerCmdExec.resourceWithOptionalAuthConfig(AbstrDockerCmdExec.java:84)
at …
```
=> fix: Add Guava dependency explicitly

src/main/java/com/sysdig/jenkins/plugins/sysdig/log/ConsoleLog.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/log/SysdigLogger.java
The logDebug(msg,throwable) method was printing the stacktrace even if DEBUG option was disabled, causing the logs to show a captured error for backend scanning when there where retries.
=> Fix a stacktrace that is printed even if log debug is disabled

pom.xml, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/ContainerRunnerFactory.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientContainerFactory.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientRunner.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java, src/test/java/FullWorkflowTests.java, src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutorTests.java
* Bump docker-java to 3.2.7
* Change docker-java transport to Apache HttpClient 5, and honor the DOCKER_HOST, DOCKER_TLS_VERIFY and DOCKER_CERT_PATH variables to be able to connect to docker via tcp:// and using TLS.
=> feat: support DOCKER_HOST for dind scenarios

src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java, src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutorTests.java
New inline-scan 2.3 changed the path where the info.log is located, so the real-time output of the container during the execution was missing (although the scan was performed correctly, as the final JSON output is still processed).
This PR uses the new path, and also allows overriding the container image name via an environment variable, which can be used to pin old version of the inline-scan container and revert to an older version in case there are compatibility issues in new releases. It also allows use in air-gapped environments.
=> Fix inline-scan 2.3 logs and image override

README.md, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java
In the current inline-scan container, if --verbose is enabled (when debug: true is set in the plugin), part of the analyzer output can end up in the stdout instead of stderr, causing an error parsing the JSON (as the stdout is expected to be a valid JSON).
This workaround ignores leaked lines in stdout to be able to work with debug enabled and the current version of the inline scan (once a new version is released, the fix won't be needed).
Also, get the stderr output from the container (when --verbose is set) in the DEBUG log level instead of INFO.
=> fix: workaround for messed JSON output with current inline-scan version

src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/Scanner.java, src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/ScannerTests.java
There are some edge cases where the digest key in the scan report does not match the local digest detected by the inline scanner. The plugin should ignore the digest in the report, if it doesn't match the image digest, and just parse the results.
https://sysdig.atlassian.net/browse/SSPROD-6906
https://sysdig.atlassian.net/browse/ESC-703
=> fix: accept scan report even if there is a digest mismatch

src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/Container.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientContainer.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientRunner.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java, src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutorTests.java
When providing a Dockerfile, it is bind mounted into /tmp/Dockerfile in the inline-scan container. This doesn't work if the docker daemon is not running in the agent, but in a remote host (for example, if we are mounting the docker.sock in the agent).
Instead of mounting the file, copy it inside the container.
https://sysdig.atlassian.net/browse/SSPROD-6237
=> fix: copy Dockerfile inside container instead of bind mount

src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigBuilderExecutor.java, src/test/java/FullWorkflowTests.java
The bailOnFail option was ignored if bailOnPluginFail was not unchecked. Fix this condition.
https://sysdig.atlassian.net/browse/SSPROD-7303
=> Fix bailOnFail being ignored if not used along bailOnPluginFail

src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder.java
The Freestyle job step was not correctly honoring environment variables set by the InjectEnv plugin.
Use run.getBuildEnvironment() method to get the variables from all EnvironmentContributors and have the expected behavior.
(cherry picked from commit bc1977824c1425d6cdbf1170e4aa321b99e0a605)
=> Use run.getEnvironment to fetch env vars from EnvironmentContributors

README.md, pom.xml, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/Container.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientContainer.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientRunner.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java
- Updates `docker-java` and relative dependencies to latest version
- Do scheduled pings during the scanning command execution, by specifying the  `DOCKER_CMD_EXEC_PING_DELAY` env-var
- Adds support for both a connection and response timeout, each with a corresponding env-var
- Updates README
=> fix: customize connection timeout and allow ping [SSPROD-11248]

pom.xml
Trying to fix the issue:
```
...
2022-05-03T21:46:44.474 INFO   SysdigSecurePlugin Completed Sysdig Secure Container Image Scanner step
FATAL: org/apache/commons/lang3/BooleanUtils
java.lang.NoClassDefFoundError: org/apache/commons/lang3/BooleanUtils
at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.build(DefaultDockerClientConfig.java:438)
at com.sysdig.jenkins.plugins.sysdig.containerrunner.DockerClientRunner.<init>(DockerClientRunner.java:43)
at com.sysdig.jenkins.plugins.sysdig.containerrunner.DockerClientContainerFactory.getContainerRunner(DockerClientContainerFactory.java:11)
at com.sysdig.jenkins.plugins.sysdig.scanner.InlineScannerRemoteExecutor.call(InlineScannerRemoteExecutor.java:87)
at com.sysdig.jenkins.plugins.sysdig.scanner.InlineScannerRemoteExecutor.call(Inli …
```
=> Add explicit dependency to apache.commons.lang3 for docker-java-core

src/main/java/com/sysdig/jenkins/plugins/sysdig/Util.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/ContainerRunnerFactory.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientContainerFactory.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientRunner.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java, src/test/java/FullWorkflowTests.java, src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutorTests.java
The env variable `DOCKER_HOST` was not taken into account when mounting a volume, the volume was mounted to an hardcoded path instead. With the fix, the host path is read from the above mentioned env variable, if not set the default hardcoded value is used.
=> Fix bug - env variable for Daemon socket path was ignored

pom.xml, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java, src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutorTests.java
When solving a problem managing the `DOCKER_HOST` env variable (see https://github.com/jenkinsci/sysdig-secure-plugin/pull/55), tcp docker daemon case had been broken.
This PR puts back the mount of default daemon socket `"/var/run/docker.sock"`, so that if this file is present in the remote host, tcp usecase will be working again.
I have reproduced locally the issue with version 2.1.15 setting the docker host to a local tcp url (with a docker in docker behind that url), this change makes the plugin work.
=> Add back volume mounting when docker host is a tcp-like url

pom.xml, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
- Updates the `sysdig-cli-scanner` to version `1.3.1` in order to support the new Sysdig **Risks-Acceptance** feature
- Bump version of a few dependencies to latest available for our currently supported minimum Jenkins version (2.150)
=> feature: Updates cli-scanner to version 1.3.1 + update a few dependencies

src/main/java/com/sysdig/jenkins/plugins/sysdig/ReportConverter.java, src/test/java/com/sysdig/jenkins/plugins/sysdig/ReportConverterTests.java
As per title: the evaluation gate status was failing because it was not taking into consideration the newly added status (**accepted)** from the internal _scanner_
=> bugfix: Evaluation gate status is now PASS when scan-result is 'accepted'

src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineReportConverter.java
Some string representations of policy rule failures were wrong (e.g. `imageConfigLabelNotExists`).
All of them are now aligned to the same representations used in the output of the embedded scanner.
=> bugfix: adjust wrong string representation of policy rule failures in report converter

src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
Updates the embedded scanner to latest `1.3.3` version.
=> chore: updates embedded scanner to the 1.3.3 version

src/main/java/com/sysdig/jenkins/plugins/sysdig/BuildConfig.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineBuildConfig.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineBuilder.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineScanStep.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineStep.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder.java, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java, src/main/resources/com/sysdig/jenkins/plugins/sysdig/NewEngineBuilder/config.jelly, src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder/global.jelly, src/main/webapp/help/help-CliVersionToApply.html, src/main/webapp/help/help-OverrideCliVersionToApply.html
=> Add ability to specify sysdig secure cli version to use for scanning

pom.xml, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
Updates the embedded scanner to latest `1.5.0` version: this will also enable scans to appear in **VM Dashboards**.
=> chore: update embedded scanner to 1.5.0

src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
Updates the embedded scanner to latest `1.8.3` version.
=> chore: bump embedded scanner to version 1.8.3

src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
The goal of this PR is to ensure that there is enough time for all the logs generated by the process of the embedded scanner to be written to the target logs file and to be collected by the logs trailer.
- reduced the delay of the logs trailer to 200ms (from 500ms)
- added a small sleep time before stopping the trailer
=> fix: ensure that all the logs from embedded scanner have been written to file for proper retrieval by the trailer

src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
Increase the waiting time before stopping the logs-trailer to 2s, to ensure all the logs generated by the scanner process are properly collected.
=> bugfix: increase the waiting time before stopping the logs trailer to 2s

src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineReportConverter.java
This PR fixes a small issue when the `ReportConverter` was failing because of a mismanagement of the `list` item in the JSON result.
In details, when the list was empty the JSON library was throwing an error because it could not assert that the item was a JSON array indeed.
=> bugfix: ensure proper management of vuln-list inside result json [SSPROD-37247]

pom.xml, src/main/webapp/css/sysdig.css
There was some collision with CSS as the plugin loaded Bootstrap, which is used to render the table and other information. Bootstrap CSS also includes some basic styles at HTML and body levels. The new Jenkins theme in the latest version uses `rem` for the font size, and it stands for root em, which is a measurement unit that refers to the font size of the root element of a document.
So, when loading Bootstrap, it changes the root element font size. With this fix, we are saying to use the initial value of the page and remove the fixed font size
We also removed the margin for the class `page-header` that is also used by the Jenkins theme and was already styled correctly
```[tasklist]
```
=> fix(style): resolved css collision with basic theme of new jenkins

README.md, src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
This is a change that introduce the possibility to download the arm64 binary when running the Jenkins Agent on arm platform (ex: AWS Graviton EC2's).
I have updated on `README.md` the image tag to be used for building the plugin with maven otherwise with 3.3 image was giving errors regarding the dependencies.
I have built the plugin and installed on a Jenkins instance. I have build a sample pipeline that perform the scan of a given image using an AWS Graviton node as Jenkins Agent and is working:
As additional check I went inside the instance and copied the binary and confirmed that Jenkins plugin retrieved the right binary:
```
root@ip-172-31-2-1:~# cp /var/jenkins/workspace/\(Sysdig\)\ Image\ Scanning\ with\ Jenkins\ plugin\ \(pull\,\ scan\)/*/bin/inlinescan-1.10.0.bin . …
```
=> feat: Support ARM64 platform

.envrc, .gitignore, flake.lock, flake.nix, plugin.nix
This adds a nix flake to pin the JDK version to an old GraalVM 8 from 2021 by executing `nix develop`. It's required for the plugin to properly run the tests and release with `mvn release:prepare release:perform`.
Also, running `nix build` will compile the current version of the plugin with the proper JVM and output the results into `./result/sysdig-secure.hpi` and `./result/sysdig-secure.jar` so we can test it in a Jenkins instance.
=> build: add nix flake to be able to compile with old graalvm

.github/CODEOWNERS
Adds the CODEOWNERS file so we can automatically get requests on PRs opened.
=> ci: add codeowners file for automatic review request

src/main/java/com/sysdig/jenkins/plugins/sysdig/domain/vm/report/Failure.java
The previous definition is incorrect for the v1beta3 format we are using. Eventually we will change to v1.
=> fix: use correct marshalling for json result

src/main/java/com/sysdig/jenkins/plugins/sysdig/application/vm/report/PolicyEvaluationSummaryLine.java, src/test/java/com/sysdig/jenkins/plugins/sysdig/infrastructure/jenkins/vm/ui/SysdigActionPersistenceTest.java
The latest implementation of PolicyEvaluationSummaryLine being a Record broke the deserialization status of previous job executions in Jenkins that used the Sysdig Plugin. This fixes it and adds a test to avoid future regressions.
=> fix: solve error deserializating status of old jobs with sysdig
