- src/main/java/com/sysdig/jenkins/plugins/sysdig/client/SysdigSecureClientImpl.java
This PR fixes the scanning URLs, to not use the proxy to Anchore.
> fix: Correct scanning URLs

- src/main/java/com/sysdig/jenkins/plugins/sysdig/RemoteInlineScanningExecution.java
This PR allows to retrieve the digest on SELinux-enabled environments.
> fix: Allow to retrieve the digest on SELinux-enabled envs

- README.md
Update README.md to reflect latest changes like supporting DOCKER_HOST, and image override.
> chore: update README.md with latest options

- pom.xml
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutorTests.java
Merge the System environment variables with the Node env variables to support Kubernetes podtemplates and withEnv.
Jira ticket: https://sysdig.atlassian.net/browse/SSPROD-7153
> Merge System env variables with node env vars

- README.md
- pom.xml
- src/main/java/com/sysdig/jenkins/plugins/sysdig/BuildConfig.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientRunner.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java
- src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder/global.jelly
- src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutorTests.java
Add two new global options:
- Override inline-scan container image
- Force inline-scan
Jira  [SSPROD-7518]
> feat: add override inline-scan image and force inline-scan global options

- pom.xml
- src/main/java/com/sysdig/jenkins/plugins/sysdig/BuildWorker.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/ReportConverter.java
- src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigAction/index.jelly
- src/main/webapp/css/sysdig.css
- src/main/webapp/js/renderOutput.js
* Some cleanup in HTML reports, and include Publish and Fix date when provided in the report.
* Include raw vulnerability JSON report as build artifact
> [SSPROD-8229] Pub/fix date in report and raw report artifact

- README.md
- pom.xml
- src/main/java/com/sysdig/jenkins/plugins/sysdig/BuildConfig.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigScanStep.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigStep.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/ContainerRunner.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientContainer.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/containerrunner/DockerClientRunner.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutor.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/Scanner.java
- src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder/config.jelly
- src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigBuilder/global.jelly
- src/test/java/FullWorkflowTests.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/InlineScannerRemoteExecutorTests.java
Add options to run the inline-scanner as a specific user (-u option for Docker) and to add additional parameters to the inline-scan container.
> Add runAsUser and extraParameter options

- README.md
Update README to include links for inline-scanning examples without docker
> Update README to add dockerless examples link

- pom.xml
This will (probably) fix a timeout issue when sending analysis result to secure backend and waiting for reply.
See https://github.com/docker-java/docker-java/pull/1590
> bump docker-java to 3.2.12 to fix socket timeout issue

- src/main/java/com/sysdig/jenkins/plugins/sysdig/ReportConverter.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/ImageScanningResult.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/Scanner.java
- src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigAction/index.jelly
- src/main/webapp/css/sysdig.css
- src/main/webapp/js/renderOutput.js
- src/test/java/FullWorkflowTests.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/ReportConverterTests.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/scanner/ScannerTests.java
- Filter for severity and fixable on vulnerabilities table
- Ability to download vulnerabilities table in csv format.
- Show policy name on policy table
- Display warning error when json files needed for generate tables are not present.
> Filter, csv download and policy names

- src/main/java/com/sysdig/jenkins/plugins/sysdig/ReportConverter.java
There was a '%' missing in the debug message so we cannot see the evaluation result
> Fix wrong format string in debug message

- src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineReportConverter.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
- src/main/webapp/js/renderOutput.js
> feat: bugfix, refactoring and handle image config results

- pom.xml
- src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineReportConverter.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineScanner.java
- Porting of all the fixes included in the `2.2.4-rc` (described in [this PR](https://github.com/jenkinsci/sysdig-secure-plugin/pull/62))
- Update version to `2.2.5-BETA`
> fix: porting of fixes included in the 2.2.4-rc

- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
> fix: ScannerPaths class is now serializable

- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
Updates the embedded scanner to the latest available version: **1.3.2**
> chore: updates to latest available version of the embedded scanner

- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
> chore: updates embedded scanner version to 1.3.6

- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
Bump the version of the internal embedded scanner to `1.8.5`.
> feature: bump version of embedded scanner to 1.8.5

- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
Bump of the embedded scanner to version `1.9.2`.
> feat: bump embedded scanner to 1.9.2

- src/main/java/com/sysdig/jenkins/plugins/sysdig/NewEngineReportConverter.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/ReportConverter.java
> fix: use imageTag (if available) when all policies evaluation pass

- src/main/java/com/sysdig/jenkins/plugins/sysdig/scanner/NewEngineRemoteExecutor.java
Bump of the embedded scanner to version `1.10.0`.
> feat: bump embedded scanner to 1.10.0

- .vscode/settings.json
- src/main/java/com/sysdig/jenkins/plugins/sysdig/CLIDownloadAction.java
- src/main/java/com/sysdig/jenkins/plugins/sysdig/SysdigIaCScanBuilder.java
- src/main/resources/com/sysdig/jenkins/plugins/sysdig/CLIDownloadAction/index.jelly
- src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigIaCScanBuilder/config.jelly
- src/main/resources/com/sysdig/jenkins/plugins/sysdig/SysdigIaCScanBuilder/config.properties
- src/main/webapp/help/help-path.html
- src/main/webapp/help/help-secureAPIToken.html
- src/main/webapp/help/help-sysdigEnv.html
- src/test/java/FullWorkflowTests.java
adding a new simple builder to run cli in iAc mode(since it's independent from existing code) also added actin to download latest greatest cli
> feature: iac cli scan builder

- plugin.nix
- pom.xml
As of Jan 28th 2025 the 61% plugin installs were made on Jenkins version 2.452.1 or higher for plugin versions >=2.3.0, so we don't expect it to be a breaking change for the users.
> build: update minimal jenkins version to 2.452.1

- src/test/java/com/sysdig/jenkins/plugins/sysdig/application/ui/report/PolicyReportProcessorTest.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/application/ui/report/VulnerabilityReportProcessorTest.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/application/vm/ImageScanningApplicationServiceTest.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/application/vm/ImageScanningArchiverTest.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/domain/ImageScanningResultTest.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/domain/vm/ImageScanningServiceTest.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/e2e/IaCScanE2EFreestyleTests.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/e2e/ImageScanningE2EFreestyleTests.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/e2e/ImageScanningE2EPipelineTests.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/e2e/JenkinsTestHelpers.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/infrastructure/json/PolicyEvaluationReportSerializerTest.java
- src/test/java/com/sysdig/jenkins/plugins/sysdig/infrastructure/vm/entrypoint/ConfigurationTests.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
> Migrate tests to JUnit5
